// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShowKeys
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidShowKeysPackageString = "03e205da-2ec4-4794-b66f-c6f1f09d17a0";
        public static Guid guidShowKeysPackage = new Guid(guidShowKeysPackageString);

        public const string guidShowKeysPackageCmdSetString = "b5f24a35-a66a-447f-8d56-d53b6fc8f3dc";
        public static Guid guidShowKeysPackageCmdSet = new Guid(guidShowKeysPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ShowKeysMenu = 0x1030;
        public const int ToggleIfEnabledCommandId = 0x0100;
        public const int OptionsCommandId = 0x0101;
    }
}